# Unsupervised learning

## Analysis for recommended system - Assoiated rules

--

In [ ]:
# !pip install apyori

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

from apyori import apriori

In [27]:
df = pd.read_csv('groceries.csv')

In [28]:
df.head()

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df.describe(include='object')

,Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,Item 10,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
count,9835,7676,6033,4734,3729,2874,2229,1684,1246,896,...,14,8,7,7,6,5,4,1,1,1
unique,158,151,155,153,150,137,138,140,128,120,...,13,7,6,7,5,4,3,1,1,1
top,sausage,whole milk,whole milk,whole milk,rolls/buns,soda,soda,shopping bags,soda,shopping bags,...,waffles,bottled beer,chocolate,shopping bags,hygiene articles,napkins,house keeping products,skin care,hygiene articles,candles
freq,825,654,506,315,176,150,120,76,61,49,...,2,2,2,1,2,2,2,1,1,1

In [30]:
df.shape

(9835, 33)

In [31]:
df.describe()

           Item(s)
count  9835.000000
mean      4.409456
std       3.589385
min       1.000000
25%       2.000000
50%       3.000000
75%       6.000000
max      32.000000

Всего было сделано 9835 покупок
Самый большой чек - 32 товара, самый маленький - 1 товар.
Средний чек - 3 - 4 товара.

In [33]:
# заполнение пропусков последним значением в строке

df1 = df.ffill(axis=1)

In [34]:
df1.set_index('Item(s)', inplace=True)

In [35]:
df1.head()

,Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,Item 10,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
Item(s),,,,,,,,,,,,,,,,,,,,,
4,citrus fruit,semi-finished bread,margarine,ready soups,ready soups,ready soups,ready soups,ready soups,ready soups,ready soups,...,ready soups,ready soups,ready soups,ready soups,ready soups,ready soups,ready soups,ready soups,ready soups,ready soups
3,tropical fruit,yogurt,coffee,coffee,coffee,coffee,coffee,coffee,coffee,coffee,...,coffee,coffee,coffee,coffee,coffee,coffee,coffee,coffee,coffee,coffee
1,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,...,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk,whole milk
4,pip fruit,yogurt,cream cheese,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,...,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads,meat spreads
4,other vegetables,whole milk,condensed milk,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,...,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product,long life bakery product

In [63]:
transactions = []
for i in range(0, 9835):
    transactions.append([str(df1.values[i, j]) for j in range(0, 32) ])

In [88]:
result = apriori(transactions, min_support=0.0045, min_confidence=0.2, min_lift=3, min_lenght=2)

In [89]:
paires = pd.DataFrame(columns=['Base Item', 'Add Item', 'Rule', 'Support', 'Confidence', 'Lift'])

for item in result:
    pair = item[0]
    items = [x for x in pair]
    
    add_item = items[0]
    base_item = items[1]
    
    rules = items[0] + " -> " + items[1]
    paires = paires.append(
                        {
                            'Base Item': str(items[1]),
                            'Add Item': str(items[0]),
                            'Rule': rules, 
                            'Support': str(item[1]), 
                            'Confidence': str(item[2][0][2]), 
                            'Lift': str(item[2][0][3])
                        }, ignore_index=True
                    )

In [90]:
# вывод пар товаров

paires

,Base Item,Add Item,Rule,Support,Confidence,Lift
0,baking powder,whipped/sour cream,whipped/sour cream -> baking powder,0.004575495678698526,0.25862068965517243,3.607850330154072
1,beef,root vegetables,root vegetables -> beef,0.017386883579054397,0.3313953488372093,3.0403668431100312
2,whipped/sour cream,berries,berries -> whipped/sour cream,0.009049313675648195,0.27217125382262997,3.796885505454703
3,bottled beer,liquor,liquor -> bottled beer,0.004677173360447382,0.4220183486238532,5.240594013529793
4,red/blush wine,bottled beer,bottled beer -> red/blush wine,0.004880528723945094,0.253968253968254,3.1537598204264876
...,...,...,...,...,...,...
59,other vegetables,whole milk,whole milk -> other vegetables,0.007829181494661922,0.3031496062992126,4.050918991783636
60,other vegetables,whole milk,whole milk -> other vegetables,0.007625826131164209,0.21246458923512745,3.7923579584890716
61,whole milk,other vegetables,other vegetables -> whole milk,0.005592272496187087,0.2696078431372549,3.602708066922421
62,rolls/buns,whole milk,whole milk -> rolls/buns,0.004880528723945094,0.4444444444444445,3.1859410430839
63,tropical fruit,whole milk,whole milk -> tropical fruit,0.0056939501779359435,0.2705314009661836,4.828813663343767

In [91]:
# Определение самых продаваемых товаров

pairs_sort = paires.sort_values(by=['Support'], ascending=False)
pairs_sort

,Base Item,Add Item,Rule,Support,Confidence,Lift
1,beef,root vegetables,root vegetables -> beef,0.017386883579054397,0.3313953488372093,3.0403668431100312
37,other vegetables,tropical fruit,tropical fruit -> other vegetables,0.012302999491611592,0.34277620396600567,3.144779819035136
20,other vegetables,citrus fruit,citrus fruit -> other vegetables,0.010371123538383325,0.3591549295774648,3.295045459323103
39,yogurt,other vegetables,other vegetables -> yogurt,0.010167768174885612,0.23419203747072598,3.2670619695384255
35,other vegetables,pip fruit,pip fruit -> other vegetables,0.00945602440264362,0.3618677042801557,3.4486132476698947
...,...,...,...,...,...,...
16,yogurt,tropical fruit,tropical fruit -> yogurt,0.004575495678698526,0.45918367346938777,3.291597251145356
43,root vegetables,tropical fruit,tropical fruit -> root vegetables,0.004575495678698526,0.2173913043478261,3.032685784767191
24,yogurt,citrus fruit,citrus fruit -> yogurt,0.004575495678698526,0.42056074766355145,3.01473393095556
28,yogurt,curd,curd -> yogurt,0.004575495678698526,0.43689320388349523,3.131810976817912
0,baking powder,whipped/sour cream,whipped/sour cream -> baking powder,0.004575495678698526,0.25862068965517243,3.607850330154072

In [99]:
print('Топ-3 продукти, що продаються')
pairs_sort['Base Item'].head(4).unique()

array(['beef', 'other vegetables', 'yogurt'], dtype=object)

In [101]:
# Список пор продаваемых товаров

paires2 = paires.sort_values(by=['Lift'], ascending=False)
paires2

,Base Item,Add Item,Rule,Support,Confidence,Lift
5,flour,sugar,sugar -> flour,0.00498220640569395,0.28654970760233917,8.46311223504206
57,other vegetables,tropical fruit,tropical fruit -> other vegetables,0.00498220640569395,0.23671497584541062,5.452205591193474
3,bottled beer,liquor,liquor -> bottled beer,0.004677173360447382,0.4220183486238532,5.240594013529793
63,tropical fruit,whole milk,whole milk -> tropical fruit,0.0056939501779359435,0.2705314009661836,4.828813663343767
56,tropical fruit,whole milk,whole milk -> tropical fruit,0.007015760040671073,0.33333333333333337,4.454257246376812
...,...,...,...,...,...,...
14,root vegetables,other vegetables,other vegetables -> root vegetables,0.0066090493136756485,0.3299492385786802,3.027099590878097
18,yogurt,other vegetables,other vegetables -> yogurt,0.004880528723945094,0.5853658536585367,3.0252617817822953
30,domestic eggs,other vegetables,other vegetables -> domestic eggs,0.007320793085917641,0.32876712328767127,3.016254344714783
24,yogurt,citrus fruit,citrus fruit -> yogurt,0.004575495678698526,0.42056074766355145,3.01473393095556
44,root vegetables,tropical fruit,tropical fruit -> root vegetables,0.00813421453990849,0.31496062992125984,3.00158701092596

In [105]:
print('Топ-2 пары продуктов')
paires2['Rule'].head(2).unique()

Вывести топ-2 пары продуктов

array(['sugar -> flour', 'tropical fruit -> other vegetables'],
      dtype=object)

В исходном наборе данных нет информации о ценах, о дне (праздник, выходной, будний день) и о времени совершения транзакций, о том, были ли в этот день маркетинговые активности или нет.
Я буду исходить из допущения, что данные взяты за обычный будний день, маркетинговые мероприятие (акции, рассылки и т.д.) не проводились какое-то время, т.е. данные "базовые".
Исходя из полученныъ результатов можно сказать, что:
- Для самых продаваемых продуктов можно увеличить маржу и не включать эти продукты в рекламные акции и рассылки
- Самые "сильные пары" продуктов можно использоваь для продвижения нового продукта этой же товарной группы, и еще для оптимального размещения продуктов на полке (если это формат обычного ритейла).
- Для онлайн коммерции на этой инфо можно построить рекомендательную систему.